### ISSUE TITLE
[PROBLEM] Can not install devkit on win10

### ISSUE THREAD

**Issue by taka9000** [oneclick/rubyinstaller2#113]
C:\>cd devkit

C:\devkit>ruby dk.rb init
C:/Ruby22-x64/lib/ruby/2.2.0/win32/registry.rb:71:in `find': unknown encoding name - CP720 (ArgumentError)
        from C:/Ruby22-x64/lib/ruby/2.2.0/win32/registry.rb:71:in `<module:Win32>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/win32/registry.rb:3:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from dk.rb:1:in `<main>'

**Comment by larskanis** [comment]
Did chcp fix your issue?
