### ISSUE TITLE
Fail to connect rubygems.org

### ISSUE THREAD

**Issue by Olimiya** [oneclick/rubyinstaller2#271]
## What problems are you experiencing?
After my first successfully install ruby and use jekyll, and i dont't know why i cannot connect rubygems.org. I reinstall rubyinstaller. And I cannot see anythin of the gem sources. 
When I use gem sources --add   https://rubygems.org, error comes:
Error fetching https://rubygems.org:
        Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect (https://rubygems.org/specs.4.8.gz)

And i use check.rb to see why, here is the result: 
Ruby:           3.1.1p18 (2022-02-18 revision 53f5fc4236a754ddf94b20dbb70ab63bd5109b18) [x64-mingw-ucrt]
RubyGems:       3.3.7
Bundler:        2.3.7
Compiled with:  OpenSSL 1.1.1m  14 Dec 2021
Loaded version: OpenSSL 1.1.1m  14 Dec 2021
SSL_CERT_FILE:  F:/Ruby31-x64/ssl/cert.pem
SSL_CERT_DIR:   F:/Ruby31-x64/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (Net::OpenTimeout)
RubyGems connection to rubygems.org:      failed  ❌  (Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect (https://rubygems.org))
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Even worse, we're not sure why. 😕

Here's the full error information:
Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect
  F:/Ruby31-x64/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock'
  F:/Ruby31-x64/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'
  F:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:1048:in `connect'
  F:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
  F:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:971:in `start'
  check.rb:101:in `<main>'

You might have more luck using Mislav's SSL doctor.rb script. You can get it here:
https://github.com/mislav/ssl-tools/blob/8b3dec4/doctor.rb
Read more about the script and how to use it in this blog post:
https://mislav.net/2013/07/ruby-openssl/
F:/Ruby31-x64/lib/ruby/3.1.0/net/protocol.rb:46:in `connect_nonblock': An existing connection was forcibly closed by the remote host. - SSL_connect (Errno::ECONNRESET)
        from F:/Ruby31-x64/lib/ruby/3.1.0/net/protocol.rb:46:in `ssl_socket_connect'
        from F:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:1048:in `connect'
        from F:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
        from F:/Ruby31-x64/lib/ruby/3.1.0/net/http.rb:971:in `start'

## Steps to reproduce
I don't know how.
I install successfully once, and i install jekyll and bundler, and then i install jekll-site-map, and failed. After that, i search a lot, and do a lot things. Maybe the command below is bad. After do so, the source of gem seems empty.
gem source -r https://rubygems.org/
gem source -a http://rubygems.org/
gem update --system
gem source -r http://rubygems.org/
gem source -a https://rubygems.org/

## What's the output from `ridk version`?
Shown below:
---
ruby:
  path: F:/Ruby31-x64
  version: 3.1.1
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.1-1
  git_commit: d9d39f1
msys2:
  path: F:\Ruby31-x64\msys64
cc: gcc (Rev9, Built by MSYS2 project) 11.2.0
sh: GNU bash, version 5.1.8(1)-release (x86_64-pc-msys)
os: Microsoft Windows [�汾 10.0.19044.1586]

Any advice on it will be appreciated!

**Comment by Olimiya** [comment]
i successully do so when i change the source to
 gem sources --add https://mirrors.tuna.tsinghua.edu.cn/rubygems/
