### ISSUE TITLE
Unable to install Jekyll on Windows 10 System

### ISSUE THREAD

**Issue by dfcoffin** [oneclick/rubyinstaller2#351]
## What problems are you experiencing?
PS C:\Users\donal> gem install jekyll bundler
ERROR:  While executing gem ... (Gem::Package::FormatError)
    package metadata is missing in C:/Ruby32-x64/lib/ruby/gems/3.2.0/cache/concurrent-ruby-1.2.2.gem
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/package.rb:687:in `verify_files'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/package.rb:613:in `block (2 levels) in verify'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/package/tar_reader.rb:27:in `new'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/package.rb:610:in `block in verify'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/package/file_source.rb:29:in `open'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/package/file_source.rb:29:in `with_read_io'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/package.rb:609:in `verify'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/package.rb:590:in `spec'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:287:in `spec'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:716:in `verify_spec'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:906:in `pre_install_checks'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/installer.rb:302:in `install'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/resolver/specification.rb:104:in `install'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/request_set.rb:194:in `block in install'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/request_set.rb:182:in `each'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/request_set.rb:182:in `install'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/commands/install_command.rb:214:in `install_gem'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/commands/install_command.rb:230:in `block in install_gems'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `each'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `install_gems'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/commands/install_command.rb:169:in `execute'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/command.rb:327:in `invoke_with_build_args'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/command_manager.rb:252:in `invoke_command'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/command_manager.rb:192:in `process_args'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/command_manager.rb:150:in `run'
        C:/Ruby32-x64/lib/ruby/3.2.0/rubygems/gem_runner.rb:51:in `run'
        C:/Ruby32-x64/bin/gem.cmd:18:in `<main>'

## Steps to reproduce
gem install jekyll bundler

## What's the output from `ridk version`?
ruby:
  path: C:/Ruby32-x64
  version: 3.2.2
  platform: x64-mingw-ucrt
  cc: gcc.exe (Rev10, Built by MSYS2 project) 12.2.0
ruby_installer:
  package_version: 3.2.2-1
  git_commit: 83df213
msys2:
  path: C:\Ruby32-x64\msys64
cc: gcc (Rev1, Built by MSYS2 project) 13.2.0
sh: GNU bash, version 5.2.15(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19045.3208]

**Comment by mohits** [comment]
I have a slightly older version of everything (but still 3.2.0) and everything works as expected. Could you try again and see if it stays the same?

```
$ ridk version
---
ruby:
  path: C:/Ruby32-x64
  version: 3.2.0
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.2.0-1
  git_commit: 5507d7c
msys2:
  path: C:\Ruby32-x64\msys64
cc: gcc (Rev7, Built by MSYS2 project) 12.2.0
sh: GNU bash, version 5.2.9(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19045.3208]
```

**Comment by dfcoffin** [comment]
I successfully installed jekyll on my Windows 10 using the "gem install jekyll bundler" command.  But attempting to use ridk version failed:

```
donal@DESKTOP-GLIN45Q MINGW64 ~
$ gem -v
3.3.26

donal@DESKTOP-GLIN45Q MINGW64 ~
$ ridk version
bash: ridk: command not found

donal@DESKTOP-GLIN45Q MINGW64 ~
$ jekyll -v
jekyll 4.3.2

donal@DESKTOP-GLIN45Q MINGW64 ~
$ ruby -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [x64-mingw-ucrt]
```

**Comment by MSP-Greg** [comment]
> But attempting to use ridk version failed

So, you're using the bash shell.  Is there a file named 'ridk' in your path?  Probably not, since RubyInstaller builds do not provide one.  `ridk.cmd version` works, not sure about other arguments.

I think it's really designed to be used with a Windows shell.

**Comment by dfcoffin** [comment]
This is the results of running ridk install usine Powershell:

```
PS C:\Users\donal> ridk install
 _____       _           _____           _        _ _         ___
|  __ \     | |         |_   _|         | |      | | |       |__ \
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ /
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _
                   |___/          _|_ _  __   | | o __  _| _     _
                                   | (_) |    |^| | | |(_|(_)\^/_>

   1 - MSYS2 base installation
   2 - MSYS2 system update (optional)
   3 - MSYS2 and MINGW development toolchain

Which components shall be installed? If unsure press ENTER [1,3] 3

> sh -lc true
MSYS2 seems to be properly installed
Install MSYS2 and MINGW development toolchain ...
> pacman -S --needed --noconfirm autoconf autogen automake-wrapper diffutils file gawk grep libtool m4 make patch sed texinfo texinfo-tex wget mingw-w64-ucrt-x86_64-binutils mingw-w64-ucrt-x86_64-crt-git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-gcc-libs mingw-w64-ucrt-x86_64-headers-git mingw-w64-ucrt-x86_64-libmangle-git mingw-w64-ucrt-x86_64-libwinpthread-git mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-tools-git mingw-w64-ucrt-x86_64-winpthreads-git pkgconf mingw-w64-ucrt-x86_64-pkgconf
warning: autoconf-wrapper-20221207-1 is up to date -- skipping
warning: autogen-5.18.16-4 is up to date -- skipping
warning: automake-wrapper-20221207-1 is up to date -- skipping
warning: diffutils-3.9-1 is up to date -- skipping
warning: file-5.44-5 is up to date -- skipping
warning: gawk-5.2.1-2 is up to date -- skipping
warning: grep-1~3.0-6 is up to date -- skipping
warning: libtool-2.4.7-3 is up to date -- skipping
warning: m4-1.4.19-2 is up to date -- skipping
warning: make-4.4.1-1 is up to date -- skipping
warning: patch-2.7.6-2 is up to date -- skipping
warning: sed-4.9-1 is up to date -- skipping
warning: texinfo-7.0.3-1 is up to date -- skipping
warning: texinfo-tex-7.0.3-1 is up to date -- skipping
warning: wget-1.21.3-2 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-binutils-2.40-2 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-crt-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-gcc-12.2.0-10 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-gcc-libs-12.2.0-10 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-headers-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-libmangle-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-libwinpthread-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-make-4.4-2 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-tools-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-winpthreads-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: pkgconf-1.9.4-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-pkgconf-1~1.8.0-2 is up to date -- skipping
 there is nothing to do
Install MSYS2 and MINGW development toolchain succeeded

You can use 'ridk enable' to activate the MSYS2 tools on the command prompt.

   1 - MSYS2 base installation
   2 - MSYS2 system update (optional)
   3 - MSYS2 and MINGW development toolchain

Which components shall be installed? If unsure press ENTER []
PS C:\Users\donal> ridk version
---
ruby:
  path: C:/Ruby31-x64
  version: 3.1.4
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.4-1
  git_commit: 83df213
msys2:
  path: C:\Ruby31-x64\msys64
cc: gcc (Rev10, Built by MSYS2 project) 12.2.0
sh: GNU bash, version 5.2.15(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19045.3324]
```

**Comment by MSP-Greg** [comment]
@dfcoffin

Thanks.

A quick look shows everything seems ok.

> package metadata is missing in C:/Ruby32-x64/lib/ruby/gems/3.2.0/cache/concurrent-ruby-1.2.2.gem

Try deleting that file and reinstalling.  I normally use ruby master, and `concurrent-ruby-1.2.2.gem` installed fine.  The cache is just that, RubyGems will download the file if it can't find it.

**Comment by dfcoffin** [comment]
I deleted C:/Ruby32-x64/lib/ruby/gems/3.2.0/cache/concurrent-ruby-1.2.2.gem and reinstalled.

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Cannot load PSReadline module.  Console is running without PSReadline.
PS C:\Users\donal> ridk install
 _____       _           _____           _        _ _         ___
|  __ \     | |         |_   _|         | |      | | |       |__ \
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ /
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _
                   |___/          _|_ _  __   | | o __  _| _     _
                                   | (_) |    |^| | | |(_|(_)\^/_>

   1 - MSYS2 base installation
   2 - MSYS2 system update (optional)
   3 - MSYS2 and MINGW development toolchain

Which components shall be installed? If unsure press ENTER [1,3] 3

> sh -lc true
MSYS2 seems to be properly installed
Install MSYS2 and MINGW development toolchain ...
> pacman -S --needed --noconfirm autoconf autogen automake-wrapper diffutils file gawk grep libtool m4 make patch sed texinfo texinfo-tex wget mingw-w64-ucrt-x86_64-binutils mingw-w64-ucrt-x86_64-crt-git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-gcc-libs mingw-w64-ucrt-x86_64-headers-git mingw-w64-ucrt-x86_64-libmangle-git mingw-w64-ucrt-x86_64-libwinpthread-git mingw-w64-ucrt-x86_64-make mingw-w64-ucrt-x86_64-tools-git mingw-w64-ucrt-x86_64-winpthreads-git pkgconf mingw-w64-ucrt-x86_64-pkgconf
warning: autoconf-wrapper-20221207-1 is up to date -- skipping
warning: autogen-5.18.16-4 is up to date -- skipping
warning: automake-wrapper-20221207-1 is up to date -- skipping
warning: diffutils-3.9-1 is up to date -- skipping
warning: file-5.44-5 is up to date -- skipping
warning: gawk-5.2.1-2 is up to date -- skipping
warning: grep-1~3.0-6 is up to date -- skipping
warning: libtool-2.4.7-3 is up to date -- skipping
warning: m4-1.4.19-2 is up to date -- skipping
warning: make-4.4.1-1 is up to date -- skipping
warning: patch-2.7.6-2 is up to date -- skipping
warning: sed-4.9-1 is up to date -- skipping
warning: texinfo-7.0.3-1 is up to date -- skipping
warning: texinfo-tex-7.0.3-1 is up to date -- skipping
warning: wget-1.21.3-2 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-binutils-2.40-2 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-crt-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-gcc-12.2.0-10 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-gcc-libs-12.2.0-10 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-headers-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-libmangle-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-libwinpthread-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-make-4.4-2 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-tools-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-winpthreads-git-10.0.0.r248.g5f566373f-1 is up to date -- skipping
warning: pkgconf-1.9.4-1 is up to date -- skipping
warning: mingw-w64-ucrt-x86_64-pkgconf-1~1.8.0-2 is up to date -- skipping
 there is nothing to do
Install MSYS2 and MINGW development toolchain succeeded

You can use 'ridk enable' to activate the MSYS2 tools on the command prompt.

   1 - MSYS2 base installation
   2 - MSYS2 system update (optional)
   3 - MSYS2 and MINGW development toolchain

Which components shall be installed? If unsure press ENTER []
PS C:\Users\donal> ridk version
---
ruby:
  path: C:/Ruby31-x64
  version: 3.1.4
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.4-1
  git_commit: 83df213
msys2:
  path: C:\Ruby31-x64\msys64
cc: gcc (Rev10, Built by MSYS2 project) 12.2.0
sh: GNU bash, version 5.2.15(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19045.3324]
PS C:\Users\donal> ridk install jekyll bundler
 _____       _           _____           _        _ _         ___
|  __ \     | |         |_   _|         | |      | | |       |__ \
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ /
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _
                   |___/          _|_ _  __   | | o __  _| _     _
                                   | (_) |    |^| | | |(_|(_)\^/_>

Can not find component "jekyll"
Can not find component "bundler"
PS C:\Users\donal>
```

The results of the risk version lists path: ruby31-x64 not ruby32-x64?

**Comment by mohits** [comment]
Hi @dfcoffin - it's 2 months since your last message. Is it all working now, or do you need some other input? If we don't hear back by 1st Nov, I will close this issue. Thanks!

**Comment by mohits** [comment]
Closing this for now.

**Comment by mohits** [comment]
I saw this in your errors.

```
Could not find gem 'tzinfo (~> 2.0.5) mingw, x64_mingw, mswin, jruby' 
```

I haven't installed Jekyll for a while but it looks like `tzinfo` needs to be installed. It could be that for some reason, it's not in the dependency path for Jekyll.

From the command line, could you install it and see if that helps?

```
gem install tzinfo
```

**Comment by mohits** [comment]
Hi @EvelinaBiserova, thanks for getting back.

Let's hope it all works. Please update us either way, and I will close the issue again.

**Comment by mohits** [comment]
I am closing this since we have not heard back from @EvelinaBiserova in a few months.
