### ISSUE TITLE
(Bundler::GemNotFound)

### ISSUE THREAD

**Issue by svpernoir** [oneclick/rubyinstaller2#366]
## What problems are you experiencing?
C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:570:in `materialize': Could not find jekyll-feed-0.16.0, jekyll-archives-2.2.1, jekyll-paginate-1.1.0, jekyll-seo-tag-2.8.0, webrick-1.7.0, rack-2.2.4, jekyll-coffeescript-2.0.0, jekyll-4.2.2, coffee-script-2.4.1, coffee-script-source-1.12.2, addressable-2.8.0, i18n-1.12.0, jekyll-sass-converter-2.2.0, liquid-4.0.3, rouge-3.29.0, terminal-table-2.0.0, execjs-2.8.1, public_suffix-4.0.7, concurrent-ruby-1.1.10, sassc-2.4.0, listen-3.7.1, unicode-display_width-1.8.0, ffi-1.15.5, rb-fsevent-0.11.1 in locally installed gems (Bundler::GemNotFound)
        from C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:203:in `specs'
        from C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/bundler/definition.rb:270:in `specs_for'
        from C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/bundler/runtime.rb:18:in `setup'
        from C:/Ruby32-x64/lib/ruby/site_ruby/3.2.0/bundler.rb:162:in `setup'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.3/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
        from C:/Ruby32-x64/lib/ruby/gems/3.2.0/gems/jekyll-4.3.3/exe/jekyll:11:in `<top (required)>'
        from C:/Ruby32-x64/bin/jekyll:32:in `load'
        from C:/Ruby32-x64/bin/jekyll:32:in `<main>'

C:\xampp\htdocs\origin>sudo apt-get update -y && sudo apt-get upgrade -y
'sudo' is not recognized as an internal or external command,
operable program or batch file.

## What's the output from `ridk version`?

Latest

**Comment by mohits** [comment]
Hi @svpernoir - the commands you are running are Linux commands and won't work in Windows as you are doing. Could you let us know what you are trying to do so that we can advise what might work on Windows.
