### ISSUE TITLE
invalid byte sequence in UTF-8?

### ISSUE THREAD

**Issue by liuestc** [oneclick/rubyinstaller2#39]
when I run `bundle install`,some err like this ``[]': invalid byte sequence in UTF-8 (ArgumentError)
`
```
D:/download/software/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler-1.14.6/lib/bler/ui/shell.rb:111:in `[]': invalid byte sequence in UTF-8 (ArgumentError)
        from D:/download/software/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler14.6/lib/bundler/ui/shell.rb:111:in `strip_leading_spaces'
        from D:/download/software/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler14.6/lib/bundler/ui/shell.rb:116:in `word_wrap'
        from D:/download/software/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler14.6/lib/bundler/ui/shell.rb:94:in `tell_me'
        from D:/download/software/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler14.6/lib/bundler/ui/shell.rb:39:in `error'
        from D:/download/software/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler14.6/lib/bundler/friendly_errors.rb:21:in `log_error'
        from D:/download/software/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler14.6/lib/bundler/friendly_errors.rb:123:in `rescue in with_friendly_errors'
        from D:/download/software/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
        from D:/download/software/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler14.6/exe/bundle:24:in `<top (required)>'
        from D:/download/software/Ruby24-x64/bin/bundle:22:in `load'
        from D:/download/software/Ruby24-x64/bin/bundle:22:in `<main>'
```

***

[I tried using this method](http://stackoverflow.com/questions/29877310/invalid-byte-sequence-in-utf-8-argumenterror),add the code into gemfile header,but still not work?

How can i solve it?

**Comment by larskanis** [comment]
Can you upload your Gemfile for inspection? Does it use UTF-8 character encoding? Can you print out the exception in `D:/download/software/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler14.6/lib/bundler/friendly_errors.rb:122` by placing a `p [e, e.backtrace]` there?

**Comment by liuestc** [comment]
@larskanis this is my gemfile
```
source 'https://rubygems.org'

gem 'rake'

# jekyll, which builds it all
# 3.0 includes sass processing
gem 'jekyll', '~>3.1'

# Jekyll extensions
gem 'jekyll-redirect-from'
gem 'jekyll-paginate'

# JSON
gem 'json'

# For `rake watch`
gem 'rb-fsevent'

# For markdown header cleanup
gem 'sanitize', '~>2.0'

# Markdown
gem 'redcarpet'

# Syntax highlighting
gem 'pygments.rb'

# Avoid having to poll for changes on Windows
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

#Live reloading
group :jekyll_plugins do
  gem 'jekyll-livereload'
end

```
***

I do not know how to debug, how can i change its encoding, err  seems to occur when install some gems

**Comment by larskanis** [comment]
@liuestc Can you print out the exception in `D:/download/software/Ruby24-x64/lib/ruby/gems/2.4.0/gems/bundler14.6/lib/bundler/friendly_errors.rb:122` by placing a `p [e, e.backtrace]` there?

**Comment by larskanis** [comment]
Closing the issue. Please reopen, if it's still unsolved.

**Comment by Phenix972** [comment]
Have you solved your problem? I have the same I can not find any solution
