### ISSUE TITLE
make failed, exit code 2

### ISSUE THREAD

**Issue by seanvree** [oneclick/rubyinstaller2#47]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?

Can't set " gem install sqlite3 --platform ruby "

## Steps to reproduce

```
C:\Sites>ridk exec pacman -S mingw-w64-x86_64-sqlite3
warning: mingw-w64-x86_64-sqlite3-3.18.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) mingw-w64-x86_64-sqlite3-3.18.0-1

Total Installed Size:  5.45 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                           [#######################################] 100%
(1/1) checking package integrity                                         [#######################################] 100%
(1/1) loading package files                                              [#######################################] 100%
(1/1) checking for file conflicts                                        [#######################################] 100%
(1/1) checking available disk space                                      [#######################################] 100%
:: Processing package changes...
(1/1) reinstalling mingw-w64-x86_64-sqlite3                              [#######################################] 100%

----------------------------------------------------------------------------------------

C:\Sites> gem install sqlite3 --platform ruby
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

    current directory: C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.13/ext/sqlite3
C:/RailsInstaller/Ruby2.3.0/bin/ruby.exe -r ./siteconf20170609-17172-17pg85l.rb extconf.rb
checking for sqlite3.h... yes
checking for pthread_create() in -lpthread... no
checking for sqlite3_libversion_number() in -lsqlite3... no
sqlite3 is missing. Install SQLite3 from http://www.sqlite.org/ first.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/RailsInstaller/Ruby2.3.0/bin/$(RUBY_BASE_NAME)
        --with-sqlite3-config
        --without-sqlite3-config
        --with-pkg-config
        --without-pkg-config
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib
        --with-pthreadlib
        --without-pthreadlib
        --with-sqlite3lib
        --without-sqlite3lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/sqlite3-1.3.13/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.13 for inspection.
Results logged to C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/sqlite3-1.3.13/gem_make.out

C:\Sites>
```

## What's the output from `ridk version`?

```
C:\WINDOWS\system32>cd C:\Ruby24-x64

C:\Ruby24-x64>ridk version
---
ruby:
  path: C:/Ruby24-x64
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-1
  git_commit: 6635d31
msys2:
  path: C:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev3, Built by MSYS2 project) 6.3.0
sh: GNU bash, version 4.3.46(2)-release (x86_64-pc-msys)

```

**Comment by MSP-Greg** [comment]
@seanvree Work in progress.  Gems need to be updated to support RI2 installs working without requiring users to add arguments for additional packages.

Thank you for the info.

See [wiki](https://github.com/oneclick/rubyinstaller2/wiki/FAQ#user-content-rails) for immediate solution.

**Comment by seanvree** [comment]
@MSP-Greg  - 

Thanks, 

I can run the three commands 

```
ridk exec pacman -S mingw-w64-i686-sqlite3 mingw-w64-i686-libxslt      # 32 bit Ruby
ridk exec pacman -S mingw-w64-x86_64-sqlite3 mingw-w64-x86_64-libxslt  # 64 bit Ruby
bundle config force_ruby_platform true
bundle config build.nokogiri --use-system-libraries
```

But when I run "bundle install" I still get the exit code 1 when installing sqlite3  ?

Is there any solution to this?

**Comment by MSP-Greg** [comment]
@seanvree 

Sorry, someday I'm going to load Rails, but I've been working on other things.  Anyway, does the following work?

```
gem install sqlite3 --platform ruby --use-system-libraries
```

**Comment by seanvree** [comment]
@MSP-Greg  - NO

```
C:\Sites\Plex-Board>gem install sqlite3 --platform ruby --use-system-libraries
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --use-system-libraries

C:\Sites\Plex-Board>
```

**Comment by MSP-Greg** [comment]
@seanvree 

Odd.  I'll look in to the error code.  I just installed the gem with two lines --
```
E:\>ridk exec pacman -S mingw-w64-x86_64-sqlite3
<< info, prompt, confirm >>
E:\>gem install sqlite3 --platform ruby --use-system-libraries
```

then
```
E:\>irb
irb(main):001:0> require 'sqlite3'
=> true
irb(main):002:0> SQLite3::VERSION
=> "1.3.13"
```

**Comment by MSP-Greg** [comment]
@seanvree 

Sorry, I was in the middle of some other very frustrating issues,  I've got most of gem config options in my .gemrc file.  My .gemrc file shows
```
--platform ruby -- --use-system-libraries
```
So, instead of
```
gem install sqlite3 --platform ruby --use-system-libraries
```
try
```
gem install sqlite3 --platform ruby -- --use-system-libraries
```

**Comment by MSP-Greg** [comment]
@seanvree 

I just googled `--use-system-libraries` to check correct syntax, Nokogiri showed the following:

```
# using gem
gem install nokogiri -- --use-system-libraries

#using bundler
bundle config build.nokogiri --use-system-libraries
bundle install
```
So, gem requires the extra set of `--`, bundler does not. Again, sorry for the error.

**Comment by seanvree** [comment]
@MSP-Greg  - 

Okay, let me ask you this. does it matter what the working dir is when I run the command?

Also, are you using the Ruby and Rails CMD prompt? or WIN CMD prompt when you run it?

this is what I get when I run it from the Ruby and Rails prompt: (Exit code 1)

```
# Rails Environment Configuration.
C:/RailsInstaller/scripts/config_check.rb:28:in ``': No such file or directory - C:/RailsInstaller/Git/bin/git.exe config --global user.name (Errno::ENOENT)
        from C:/RailsInstaller/scripts/config_check.rb:28:in `run'
        from C:/RailsInstaller/scripts/config_check.rb:40:in `git_config'
        from C:/RailsInstaller/scripts/config_check.rb:49:in `block in <main>'
        from C:/RailsInstaller/scripts/config_check.rb:48:in `each'
        from C:/RailsInstaller/scripts/config_check.rb:48:in `<main>'

C:\Sites>cd plex-board

C:\Sites\Plex-Board>gem install sqlite3 --platform ruby -- --use-system-libraries
Temporarily enhancing PATH to include DevKit...
Building native extensions with: '--use-system-libraries'
This could take a while...
ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

    current directory: C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.13/ext/sqlite3
C:/RailsInstaller/Ruby2.3.0/bin/ruby.exe -r ./siteconf20170609-27716-xfv1vm.rb extconf.rb --use-system-libraries
checking for sqlite3.h... yes
checking for pthread_create() in -lpthread... no
checking for sqlite3_libversion_number() in -lsqlite3... no
sqlite3 is missing. Install SQLite3 from http://www.sqlite.org/ first.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/RailsInstaller/Ruby2.3.0/bin/$(RUBY_BASE_NAME)
        --with-sqlite3-config
        --without-sqlite3-config
        --with-pkg-config
        --without-pkg-config
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib
        --with-pthreadlib
        --without-pthreadlib
        --with-sqlite3lib
        --without-sqlite3lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/sqlite3-1.3.13/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/sqlite3-1.3.13 for inspection.
Results logged to C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/extensions/x86-mingw32/2.3.0/sqlite3-1.3.13/gem_make.out

C:\Sites\Plex-Board>
```

This is what I get when I run it from the WIN CMD prompt:

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd C:\Sites\Plex-Board

C:\Sites\Plex-Board>gem install sqlite3 --platform ruby -- --use-system-libraries
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions with: '--use-system-libraries'
This could take a while...
ERROR:  Error installing sqlite3:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sqlite3-1.3.13/ext/sqlite3
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170609-17272-i4ohai.rb extconf.rb --use-system-libraries
checking for sqlite3.h... yes
checking for pthread_create() in -lpthread... yes
checking for sqlite3_libversion_number() in -lsqlite3... yes
checking for rb_proc_arity()... yes
checking for rb_integer_pack()... yes
checking for sqlite3_initialize()... yes
checking for sqlite3_backup_init()... yes
checking for sqlite3_column_database_name()... yes
checking for sqlite3_enable_load_extension()... yes
checking for sqlite3_load_extension()... yes
checking for sqlite3_open_v2()... yes
checking for sqlite3_prepare_v2()... yes
checking for sqlite3_int64 in sqlite3.h... yes
checking for sqlite3_uint64 in sqlite3.h... yes
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sqlite3-1.3.13/ext/sqlite3
make "DESTDIR=" clean

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sqlite3-1.3.13/ext/sqlite3
make "DESTDIR="
generating sqlite3_native-x64-mingw32.def
make: *** No rule to make target '/C/Ruby24-x64/include/ruby-2.4.0/ruby.h', needed by 'backup.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/sqlite3-1.3.13 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/sqlite3-1.3.13/gem_make.out

C:\Sites\Plex-Board>
```

**Comment by MSP-Greg** [comment]
@seanvree 

As I mentioned, I don't have Rails installed, so everything is windows command prompt.

I forgot to mention that `ridk version` seems fine.  If you have a chance, I'd be interested in seeing what/if it reports from the Rails prompt, as it might not be in the path

1. Rails prompt - it seems there's another ruby install at `C:/RailsInstaller/Ruby2.3.0/bin/ruby.exe`, so that might cause some issues.  At present Ruby 2.3 is RubyInstaller, Ruby 2.4 is RubyInstaller2.  Very different.

2. Normal cmd prompt - install got quite a bit further, as it started the build process and got to 'Creating Makefile'.

I thought Rails requires Nokogiri, did that install correctly?  It's got a bin, so from command prompt
```
nokogiri --version
```

Long story, but I've been running ruby 2.5 trunk for a while, and although the build system is different, I use the RubyInstaller2 (RI2) runtime code.  I've also got quite a few extension gems installed, which are gems that contain c source.  Some I don't even use, I installed to verify that they would build/compile.  So it will work, we just need to determine what's amiss.

I'm not really a c type, so I'm not running into build problems that often.  Maybe Lars will be able to help, I'll try to check my 2.4 RI2 install tomorrow.  This maybe due to a conflict between the two Ruby installs or environment variables that Rails might have set up/changed, but I'm not sure.

**Note** - since the file `C:/RailsInstaller/Ruby2.3.0/bin/ruby.exe` exists, from the Rails prompt, what version of ruby is it loading (`ruby -v`)?

Back tomorrow...

**Comment by seanvree** [comment]
@MSP-Greg  - I really appreciate your help. 

So from the rails prompt I get:

```
C:\Sites>ridk version
---
ruby:
  path: C:/Ruby24-x64
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-1
  git_commit: 6635d31
msys2:
  path: C:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev3, Built by MSYS2 project) 6.3.0
sh: GNU bash, version 4.3.46(2)-release (x86_64-pc-msys)
```

I think you're right about the Railsinstaller using it's OWN Ruby from C:/RailsInstaller/Ruby2.3.0/bin/ruby.exe

However, I'm not sure how to configure that so it uses the ruby from c:\Ruby24-x64

Also, from the rails prompt I get:

```
C:\Sites>ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [i386-mingw32]
```

So, yes, there is two different ruby installs which is the problem.  I'll do some research how to get Rails to use the Ruby from the c:\Ruby

**Comment by seanvree** [comment]
I just figured it out.  I simply renamed the Ruby dir C:\RailsInstaller\ruby2.3 to ruby2.3.old.  Now BOTH the rails prompt and windows prompt are using the same version from the same PATH. 

testing right now, I'll update in a bit.

**Comment by seanvree** [comment]
Okay, so got a bit futher, but I'm still failing on nio4r:

this is from the windows prompt:

```
c:\Sites\Plex-Board>bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Using rake 12.0.0
Using concurrent-ruby 1.0.5
Using i18n 0.8.4
Using minitest 5.10.2
Using thread_safe 0.3.6
Using builder 3.2.3
Using erubi 1.6.0
Using mini_portile2 2.1.0
Using rack 2.0.3
Fetching nio4r 2.1.0
Installing nio4r 2.1.0 with native extensions
Using websocket-extensions 0.1.2
Using mime-types-data 3.2016.0521
Using arel 8.0.0
Using method_source 0.8.2
Using thor 0.19.4
Using bundler 1.15.1
Fetching sqlite3 1.3.13
Installing sqlite3 1.3.13 with native extensions
Using sass 3.4.24
Using tilt 2.0.7
Using execjs 2.7.0
Using coffee-script-source 1.12.2
Using turbolinks-source 5.0.3
Using multi_json 1.12.1
Fetching json 1.8.6
Installing json 1.8.6 with native extensions
Using rdoc 4.3.0
Fetching unf_ext 0.0.7.4
Installing unf_ext 0.0.7.4 with native extensions
Using netrc 0.11.0
Using parallel 1.11.2
Using multipart-post 2.0.0
Using hashie 3.5.5
Using geocoder 1.4.4
Fetching puma 3.8.2
Installing puma 3.8.2 with native extensions
Using tzinfo 1.2.3
Fetching nokogiri 1.7.2
Installing nokogiri 1.7.2 with native extensions
Using rack-test 0.6.3
Using sprockets 3.7.1
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nio4r-2.1.0/ext/nio4r
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170610-22728-19h2rdl.rb extconf.rb
checking for unistd.h... yes
checking for sys/select.h... no
checking for poll.h... no
checking for sys/epoll.h... no
checking for sys/event.h... no
checking for port.h... no
checking for sys/resource.h... no
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nio4r-2.1.0/ext/nio4r
make "DESTDIR=" clean

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nio4r-2.1.0/ext/nio4r
make "DESTDIR="
generating nio4r_ext-x64-mingw32.def
make: *** No rule to make target '/C/Ruby24-x64/include/ruby-2.4.0/ruby.h',
needed by 'bytebuffer.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nio4r-2.1.0 for inspection.
Results logged to
C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/nio4r-2.1.0/gem_make.out

An error occurred while installing nio4r (2.1.0), and Bundler cannot continue.
Make sure that `gem install nio4r -v '2.1.0'` succeeds before bundling.

In Gemfile:
  rails was resolved to 5.1.1, which depends on
    actioncable was resolved to 5.1.1, which depends on
      nio4r

c:\Sites\Plex-Board>gem install nio4r
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing nio4r:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nio4r-2.1.0/ext/nio4r
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170610-25272-1380mgy.rb extconf.rb
checking for unistd.h... yes
checking for sys/select.h... no
checking for poll.h... no
checking for sys/epoll.h... no
checking for sys/event.h... no
checking for port.h... no
checking for sys/resource.h... no
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nio4r-2.1.0/ext/nio4r
make "DESTDIR=" clean

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nio4r-2.1.0/ext/nio4r
make "DESTDIR="
generating nio4r_ext-x64-mingw32.def
make: *** No rule to make target '/C/Ruby24-x64/include/ruby-2.4.0/ruby.h', needed by 'bytebuffer.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nio4r-2.1.0 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/nio4r-2.1.0/gem_make.out

c:\Sites\Plex-Board>nokogiri --version
'nokogiri' is not recognized as an internal or external command,
operable program or batch file.

c:\Sites\Plex-Board>nokogiri --version
'nokogiri' is not recognized as an internal or external command,
operable program or batch file.

c:\Sites\Plex-Board>
```

**Comment by MSP-Greg** [comment]
@seanvree

Glad to see you're making progress.  You asked a question, I never answered.

> Okay, let me ask you this. does it matter what the working dir is when I run the command?

A qualified no.  Without going into all the specifics, when a command is run, it may be passed environment information that has previously been set in that process (which includes a cmd window).  Another way of (simply) looking it is that every process has it's own private environment.  So, if the 'Rails prompt' is changing/affecting that environment, it may change how some commands function.

Back to nio4r and nokogiri.  nio4r starts the build but fails.  Have you tried:
```
gem install nio4r --platform ruby -- --use-system-libraries
```

I wasn't aware that nio4r upped to 2.1.0, so I just uninstalled 2.0.0, then installed 2.1.0 with the above.

**Comment by seanvree** [comment]
yeah, i don't think I have nio4r installed at all...

```
c:\Sites\Plex-Board>ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]

c:\Sites\Plex-Board>which ruby
/cygdrive/c/Ruby24-x64/bin/ruby

c:\Sites\Plex-Board>nokogiri --version
# Nokogiri (1.8.0)
    ---
    warnings: []
    nokogiri: 1.8.0
    ruby:
      version: 2.4.1
      platform: x64-mingw32
      description: ruby 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]
      engine: ruby
    libxml:
      binding: extension
      source: packaged
      libxml2_path: "/home/flavorjones/code/oss/nokogiri/ports/x86_64-w64-mingw32/libxml2/2.9.4"
      libxslt_path: "/home/flavorjones/code/oss/nokogiri/ports/x86_64-w64-mingw32/libxslt/1.1.29"
      libxml2_patches:
      - 0001-Fix-comparison-with-root-node-in-xmlXPathCmpNodes.patch
      - 0002-Fix-XPointer-paths-beginning-with-range-to.patch
      - 0003-Disallow-namespace-nodes-in-XPointer-ranges.patch
      libxslt_patches:
      - 0001-Fix-heap-overread-in-xsltFormatNumberConversion.patch
      - 0002-Check-for-integer-overflow-in-xsltAddTextString.patch
      compiled: 2.9.4
      loaded: 2.9.4

c:\Sites\Plex-Board>gem install nio4r --platform ruby -- --use-system-libraries
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions with: '--use-system-libraries'
This could take a while...
ERROR:  Error installing nio4r:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nio4r-2.1.0/ext/nio4r
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170611-17908-1g1vkxo.rb extconf.rb --use-system-libraries
checking for unistd.h... yes
checking for sys/select.h... no
checking for poll.h... no
checking for sys/epoll.h... no
checking for sys/event.h... no
checking for port.h... no
checking for sys/resource.h... no
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nio4r-2.1.0/ext/nio4r
make "DESTDIR=" clean

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nio4r-2.1.0/ext/nio4r
make "DESTDIR="
generating nio4r_ext-x64-mingw32.def
make: *** No rule to make target '/C/Ruby24-x64/include/ruby-2.4.0/ruby.h', needed by 'bytebuffer.o'.  Stop.

make failed, exit code 2

Gem files will remain installed in C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/nio4r-2.1.0 for inspection.
Results logged to C:/Ruby24-x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/nio4r-2.1.0/gem_make.out

c:\Sites\Plex-Board>

```

**Comment by larskanis** [comment]
> No rule to make target '/C/Ruby24-x64/include/ruby-2.4.0/ruby.h'

means, that the file `/C/Ruby24-x64/include/ruby-2.4.0/ruby.h` is not available and can not be generated. This is the MSYS2 notation of the path `C:/Ruby24-x64/include/ruby-2.4.0/ruby.h`. This file is installed as part of the RubyInstaller2 setup. I wonder why this file is missing on your installation?

Anyhow, without `ruby.h` no ruby extension will compile.

**Comment by seanvree** [comment]
@larskanis Yeah, that's weird, because the file is there at C:\Ruby24-x64\include\ruby-2.4.0\ruby.h

I mean, all other things ruby work on the system, it's just this one package.  If ruby.h isn't accessible, wouldn't a buch of other stuff fail?

Does that path "c:\Ruby24-x64\include\"  in the windows system path?

**Comment by seanvree** [comment]
@larskanis  - you have any more ideas about this? appreciate it!

**Comment by dmajkic** [comment]
Open MSYS shell and try to `cd /C/Ruby24-x64/include/ruby-2.4.0` and try to access `ruby.h` via `cat ruby.h`.

**Comment by seanvree** [comment]
@dmajkic 

Is this good  - 

```
Administrator@VreePlexDesktop MINGW64 ~
$ cd /C/Ruby24-x64/include/ruby-2.4.0

Administrator@VreePlexDesktop MINGW64 /C/Ruby24-x64/include/ruby-2.4.0
$ cat ruby.h
/**********************************************************************

  ruby.h -

  $Author$
  created at: Sun 10 12:06:15 Jun JST 2007

  Copyright (C) 2007-2008 Yukihiro Matsumoto

**********************************************************************/

#ifndef RUBY_H
#define RUBY_H 1

#define HAVE_RUBY_DEFINES_H     1
#define HAVE_RUBY_ENCODING_H    1
#define HAVE_RUBY_INTERN_H      1
#define HAVE_RUBY_IO_H          1
#define HAVE_RUBY_MISSING_H     1
#define HAVE_RUBY_ONIGURUMA_H   1
#define HAVE_RUBY_RE_H          1
#define HAVE_RUBY_REGEX_H       1
#define HAVE_RUBY_RUBY_H        1
#define HAVE_RUBY_ST_H          1
#define HAVE_RUBY_THREAD_H      1
#define HAVE_RUBY_UTIL_H        1
#define HAVE_RUBY_VERSION_H     1
#define HAVE_RUBY_VM_H          1
#ifdef _WIN32
#define HAVE_RUBY_WIN32_H       1
#endif

#include "ruby/ruby.h"

#endif /* RUBY_H */

Administrator@VreePlexDesktop MINGW64 /C/Ruby24-x64/include/ruby-2.4.0
$
```

**Comment by seanvree** [comment]
Hey @MSP-Greg  - do you have any more thoughts on this...or a lost cause?

THX

**Comment by MSP-Greg** [comment]
@seanvree  Kind of in the middle of some other fun, but...

I've never had any issues installing nio4r, but I've never used it.  I ran its tests, and results are not good.    Also, I've tested EM before, but now I'm getting a SEGV with its tests. 

Hence, I hope to investigate further.

**Comment by seanvree** [comment]
@MSP-Greg , cool! let me know!

**Comment by larskanis** [comment]
@seanvree The only idea I have is that there's some interference with some other MSYS or MSYS2 installation is happening. Maybe GIT or so. I did not receive a similar issue other than this. Have you been able to solve it?

**Comment by seanvree** [comment]
@larskanis  Nope. Sad to say I couldn't get it done. Moved on from rails. 

Cheers.

**Comment by thisismydesign** [comment]
I found & solved one possible cause: https://github.com/oneclick/rubyinstaller2/issues/105

**Comment by Udoy2** [comment]
Hey i am getting this problem when i try to install eventmachine-1.0.9.1 in termux app this happens 

gem install eventmachine -v 1.0.9.1
Building native extensions.  This could take a while...
ERROR:  Error installing eventmachine:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.0.9.1/ext
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20180329-31789-1wse8h8.rb extconf.rb
checking for -lcrypto... yes
checking for -lssl... yes
checking for openssl/ssl.h... yes
checking for openssl/err.h... yes
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for rb_thread_blocking_region()... no
checking for ruby/thread.h... yes
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes
checking for inotify_init() in sys/inotify.h... yes
checking for writev() in sys/uio.h... yes
checking for rb_thread_fd_select()... yes
checking for rb_fdset_t in ruby/intern.h... yes
checking for pipe2() in unistd.h... yes
checking for accept4() in sys/socket.h... yes
checking for SOCK_CLOEXEC in sys/socket.h... yes
checking for rb_wait_for_single_fd()... yes
checking for rb_enable_interrupt()... no
checking for rb_time_new()... yes
checking for sys/event.h... no
checking for epoll_create() in sys/epoll.h... yes
checking for clock_gettime()... yes
checking for CLOCK_MONOTONIC_RAW in time.h... yes
checking for CLOCK_MONOTONIC in time.h... yes
CXXFLAGS= -march=armv7-a -mfpu=neon -mfloat-abi=softfp -mthumb -Oz -Wall -Wextra -Wno-deprecated-declarations -Wno-ignored-qualifiers -Wno-unused-result -Wno-address
creating Makefile

current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.0.9.1/ext
make "DESTDIR=" clean
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/make-0.3.1/bin/make:4:in `<top (required)>': undefined local variable or method `make' for main:Object (NameError)
        from /data/data/com.termux/files/usr/bin/make:23:in `load'
        from /data/data/com.termux/files/usr/bin/make:23:in `<main>'

current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.0.9.1/ext
make "DESTDIR="
/data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/make-0.3.1/bin/make:4:in `<top (required)>': undefined local variable or method `make' for main:Object (NameError)
        from /data/data/com.termux/files/usr/bin/make:23:in `load'
        from /data/data/com.termux/files/usr/bin/make:23:in `<main>'

make failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/eventmachine-1.0.9.1 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/extensions/arm-linux/2.4.0/eventmachine-1.0.9.1/gem_make.out

I realy need help please help me
